# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
