# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waypoint_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crisisname', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('contact_information', models.CharField(blank=True, max_length=200)),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providername', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('contact_information', models.CharField(blank=True, max_length=200)),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalname', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('contact_information', models.CharField(blank=True, max_length=200)),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalname', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('contact_information', models.CharField(blank=True, max_length=200)),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('othername', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('contact_information', models.CharField(blank=True, max_length=200)),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheltername', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('contact_information', models.CharField(blank=True, max_length=200)),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
    ]
