# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waypoint_app', '0002_crisis_food_legal_medical_other_shelter'),
    ]

    operations = [
    ]
