# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waypoint_app', '0002_auto_20170104_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crisisname', models.CharField(max_length=200)),
                ('contact_information', models.CharField(blank=True, max_length=200)),
                ('second_phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providername', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('additional_contact', models.CharField(blank=True, max_length=200)),
                ('description_text', models.TextField()),
                ('food_meals', models.BooleanField()),
                ('food_pantry', models.BooleanField()),
                ('times', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalname', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('description_text', models.TextField()),
                ('refugee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalname', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('additional_contact', models.CharField(blank=True, max_length=200)),
                ('description_text', models.TextField()),
                ('general_health', models.BooleanField()),
                ('mental_health', models.BooleanField()),
                ('addiction_treatment', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheltername', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('additional_contact', models.CharField(blank=True, max_length=200)),
                ('description_text', models.TextField()),
                ('target_customers', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportname', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('target_customers', models.CharField(max_length=200)),
                ('description_text', models.TextField()),
            ],
        ),
    ]
