# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheltername', models.CharField(max_length=200)),
                ('checked', models.DateTimeField(verbose_name='date checked')),
                ('zipcode', models.IntegerField(default=0)),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
    ]
