# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeless_guide_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='checked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
