# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeless_guide_app', '0002_auto_20161228_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='checked',
        ),
        migrations.AddField(
            model_name='shelter',
            name='address',
            field=models.CharField(default='search', max_length=200),
        ),
    ]
